sonar.projectKey=jmertic_slack-release-notifier
sonar.organization=jmertic

sonar.sources=.
sonar.tests=test
sonar.exclusions=test/**, **/venv/**

# Python Coverage Report Path
sonar.python.coverage.reportPaths=coverage.xml
